/** Auto-generated by scripts/generate-saree-lens-details.mjs — do not edit manually. */
export const SAREE_LENS_DETAIL_IMAGES: Record<string, string[]> = {
  'crimson-red-georgette-saree': ['/collections/saree/details/crimson-red-georgette-saree-detail-1.jpg', '/collections/saree/details/crimson-red-georgette-saree-detail-2.jpg'],
  'maroon-bandhani-print-saree': ['/collections/saree/details/maroon-bandhani-print-saree-detail-1.jpg', '/collections/saree/details/maroon-bandhani-print-saree-detail-2.jpg'],
  'maroon-satin-silver-zari-saree': ['/collections/saree/details/maroon-satin-silver-zari-saree-detail-1.jpg', '/collections/saree/details/maroon-satin-silver-zari-saree-detail-2.jpg'],
  'mustard-olive-batik-saree': ['/collections/saree/details/mustard-olive-batik-saree-detail-1.jpg', '/collections/saree/details/mustard-olive-batik-saree-detail-2.jpg'],
  'olive-green-silk-saree': ['/collections/saree/details/olive-green-silk-saree-detail-1.jpg', '/collections/saree/details/olive-green-silk-saree-detail-2.jpg'],
  'royal-purple-gold-buta-saree': ['/collections/saree/details/royal-purple-gold-buta-saree-detail-1.jpg', '/collections/saree/details/royal-purple-gold-buta-saree-detail-2.jpg'],
}
